 DROP database BD_RABLOG;
create database BD_RABLOG;

USE BD_RABLOG;

CREATE TABLE USUARIO (
ID_USER INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50),
LOGIN VARCHAR(50) NOT NULL,
SENHA VARCHAR(50) NOT NULL
);

CREATE TABLE POSTAGEM (
ID_POSTAGEM INT PRIMARY KEY AUTO_INCREMENT,
TITULO VARCHAR(20),
TEXTO VARCHAR(1000),
COR VARCHAR(10)
);

CREATE TABLE IMAGEM (
FK_POST INT,
ID_IMAGEM INT,
NOME VARCHAR(20),
URL VARCHAR(300),
INTERNA BOOLEAN,
PRIMARY KEY AUTO_INCREMENT(FK_POST, ID_IMAGEM) ,
FOREIGN KEY(FK_POST) REFERENCES POSTAGEM(ID_POSTAGEM)
);

CREATE TABLE LOG (
ID_LOG INT PRIMARY KEY AUTO_INCREMENT,
TEXTO VARCHAR(200)
);
